version: "3.9"
services:
  api:
    build: ./api
    env_file: .env
    ports: [ "8080:8080" ]
    depends_on: [ redis, minio ]
    volumes: [ "./api:/app" ]
  worker:
    build: ./worker
    env_file: .env
    depends_on: [ redis, minio ]
    volumes: [ "./worker:/app" ]
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports: [ "5173:5173" ]
    environment:
      VITE_API_URL: http://localhost:8080
    volumes: [ "./web:/app" ]
  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports: [ "9000:9000", "9001:9001" ]
    volumes: [ "./data:/data" ]

